config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :routes, only: %i[index show create] do
    resources :bookmarks, only: [:create]
    resources :days, only: [:create]
  end

  #For Stripe Payments
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  get "hack", to: "bookings#hack", as: :hack
  #==============

  resources :bookmarks, only: %i[index edit update destroy] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: %i[index show edit update destroy]
  resources :days, only: %i[index update destroy] do
    patch "upgrade_hotel", to: "days#upgrade_hotel"
    patch "downgrade_hotel", to: "days#downgrade_hotel"
    patch "change_activity", to: "days#change_activity"
  end

  patch "update_sequence", to: "days#update_sequence"

  # resources :bookmarks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :route
  has_one :booking

  validates :route, presence: true, uniqueness: true#, message: "You have already bookmarked this route!" }
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:create]

  def index
    # test UserMailer
    # UserMailer.with(user: current_user).welcome.deliver_now

    @bookmarks = current_user.bookmarks.order(created_at: :desc).select { |bookmark| bookmark.booking.nil? }
    @booking = Booking.new
  end

  def create
    @bookmark = Bookmark.new
    @route = Route.find(params[:route_id])
    if @route.user == current_user
      @bookmark.route = @route
      if @bookmark.save
        redirect_to route_path(@route), status: :see_other
      end
    else
      new_route = @route.dup
      # add option to change dates
      new_route.user = current_user
      if new_route.save
        @route.days.each do |day|
          new_day = day.dup
          new_day.route = new_route
          new_day.save
        end
        @bookmark.route = new_route
        if @bookmark.save
          redirect_to route_path(new_route), status: :see_other
        end
      end
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_back(fallback_location: root_path)#, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:description)
  end
end

app/views/bookmarks/_bookmarks_info.html.erb
<div class="w-full mx-auto">
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
    <% @bookmarks.each do |bookmark| %>
      <div class="w-full w-80 rounded-lg pb-8 p-4">
        <a href="routes/<%= bookmark.route.id %>">
          <div class="c-card block bg-white shadow-md hover:shadow-xl rounded-lg overflow-hidden h-full flex flex-col">
            <div class="relative pb-48 overflow-hidden">
              <img class="absolute inset-0 h-full w-full object-cover p-6" src="https://source.unsplash.com/random/900x600/?<%= bookmark.route.days.first.city %>" alt="Image of city">
            </div>
            <div class="p-4 flex-grow">
              <h2 class="mt-2 mb-2 font-bold"><%= bookmark.route.destination %></h2>
              <% bookmark.route.days.limit(4).each do |day| %>
                <p class="text-sm"><%= day.name %></p>
              <% end %>
              <a href="routes/<%= bookmark.route.id %>" class="font-medium text-sm text-darkerYellow mt-2">
                View Route<span class="text-darkerYellow">&hellip;</span>
              </a>
              <div class="mt-3 flex items-center">
                <span class="text-sm font-semibold">for</span>&nbsp;<span class="font-bold text-xl"><%= bookmark.route.total_price.round(2) %></span>&nbsp;<span class="text-sm font-semibold">€</span>
              </div>
            </div>
            <div class="mx-auto p-4 border-t text-xs text-gray-700">
              <div class="mt-3">
                <p><i class="far fa-calendar-alt"></i> <%= bookmark.route.start_date.strftime('%B %d, %Y') %> - <%= bookmark.route.end_date.strftime('%B %d, %Y') %></p>
              </div>
              <div class="mx-auto mt-3 flex flex-wrap justify-between">
  <% if bookmark.booking.nil? %>
    <%= form_with url: orders_path do %>
      <%= hidden_field_tag 'bookmark_id', bookmark.id %>
      <%= submit_tag 'Book!', class: 'inline-block text-white bg-mainYellow hover:bg-darkerYellow focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 w-full md:w-auto mb-2 md:mb-0' %>
    <% end %>
  <% else %>
    <p class="inline-block text-black bg-grey-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center w-full md:w-auto mb-2 md:mb-0">
      You have already booked this trip!
    </p>
    <%= link_to "Cancel Booking", booking_path(bookmark.booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "inline-block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 w-full md:w-auto" %>
  <% end %>
  <%= link_to "Remove", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "ml-0 md:ml-2 text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800 w-full md:w-auto" %>
</div>
            </div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
</div>

app/views/bookmarks/_test_bookmar.html.erb
<% @bookmarks.each do |bookmark| %>
<div class="w-full w-80 rounded-lg pb-8 p-4">
  <a href="routes/<%= bookmark.route.id %>">
    <div class="c-card block bg-white shadow-md hover:shadow-xl rounded-lg overflow-hidden">
      <div class="relative pb-48 overflow-hidden">
        <img class="absolute inset-0 h-full w-full object-cover p-6" src="https://source.unsplash.com/random/1200x800/?<%= bookmark.route.days.first.city %>" alt="Image of city">
      </div>
      <div class="p-4">
        <h2 class="mt-2 mb-2 font-bold"><%= bookmark.route.destination %></h2>
        <% bookmark.route.days.each do |day| %>
          <p class="text-sm"><%= day.name %></p>
        <% end %>
        <a href="routes/<%= bookmark.route.id %>" class="font-medium text-sm text-darkerYellow mt-2">
          Explore<span class="text-darkerYellow">&hellip;</span>
        </a>
        <div class="mt-3 flex items-center">
          <span class="text-sm font-semibold">for</span>&nbsp;<span class="font-bold text-xl"><%= bookmark.route.total_price.round(2) %></span>&nbsp;<span class="text-sm font-semibold">€</span>
        </div>
      </div>
      <div class="p-4 border-t text-xs text-gray-700 flex justify-between">
        <div>
          <span class="flex items-center mb-1">
            <i class="far fa-clock fa-fw mr-2 text-gray-900"></i> <%= bookmark.route.days.count %> days
          </span>
          <span class="flex items-center">
            <i class="far fa-address-card fa-fw text-gray-900 mr-2"></i> VISA not needed
          </span>
        </div>
        <div class="my-auto">
          <% if bookmark.booking == nil %>
            <!-- Modal toggle -->
            <button id="bookButton" data-modal-target="defaultModal" data-modal-show="defaultModal" class="hover:scale-125 float-left mr-2 bg-mainYellow hover:bg-darkerYellow text-white text-sm font-bold rounded px-2 py-1 hover:scale-110 transition duration-500 ease-in-out">
              Book!
            </button>
            <!-- Main modal -->
            <div id="defaultModal" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] md:h-full">
              <div class="absolute w-1/3 h-full min-w-1/2 md:h-auto">
                <!-- Modal content -->
                <%= render "bookings/booking_modal", bookmark: bookmark %>
              </div>
            </div>
          <% else %>
            <div class="">
              <p class="block text-black bg-grey-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
                You have already booked this trip!
              </p>
            <%= link_to "Cancel Booking", booking_path(bookmark.booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?", class: "block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"} %>
          </div>
        <% end %>
      </div>
    </div>
  </a>
</div>
</div>
<% end %>

app/views/bookmarks/index.html.erb
<%= render "shared/navbar" %>

<div class="h-screen flex flex-col container mx-auto p-8 px-40">
  <h1 class="text-5xl font-bold py-8">Your bookmarks</h1>
  <div class="flex overflow-x-scroll pb-10 hide-scroll-bar">
    <div class="flex flex-nowrap -mx-4">
      <%= render "bookmarks_info", bookmarks: @bookmarks %>
    </div>
  </div>
</div>