config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :routes, only: %i[index show create] do
    resources :bookmarks, only: [:create]
    resources :days, only: [:create]
  end

  #For Stripe Payments
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  get "hack", to: "bookings#hack", as: :hack
  #==============

  resources :bookmarks, only: %i[index edit update destroy] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: %i[index show edit update destroy]
  resources :days, only: %i[index update destroy] do
    patch "upgrade_hotel", to: "days#upgrade_hotel"
    patch "downgrade_hotel", to: "days#downgrade_hotel"
    patch "change_activity", to: "days#change_activity"
  end

  patch "update_sequence", to: "days#update_sequence"

  # resources :bookmarks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/route.rb
class Route < ApplicationRecord
  monetize :price_cents
  belongs_to :user
  has_one :bookmark, dependent: :destroy
  has_one :booking, through: :bookmark
  has_many :days, dependent: :destroy

end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @route = Route.last
    if user_signed_in?
      @routes = current_user.routes.order(created_at: :desc)
    else
      @routes = Route.all
    end
  end

  def show
    @route = Route.find(params[:id])
    @bookmark = Bookmark.new
    @booking = Booking.new
    @days = @route.days.order(sequence: :asc)

    @countries = []
    @route.days.each do |day|
      @countries << day.nation unless @countries.include?(day.nation)
    end

    @markers = @days.map do |day|
      {
        lat: day.latitude,
        lng: day.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { day: day }),
        # logo_marker_html: render_to_string(partial: "logo_marker", locals: {day: day})
      }
    end

    # @rmarkersfirst = @days.where(id: @days.minimum(:id)).map do |day|
    #   {
    #     lat: day.latitude,
    #     lng: day.longitude,
    #     info_window_html: render_to_string(partial: "first_marker", locals: {day: day}),
    #     logo_first_marker_html: render_to_string(partial: "logo_first_marker", locals: {day: day})
    #   }
    # end
  end

  def create
    Route.all.each do |route|
      route.destroy if route.total_price == 0
    end

    @route = Route.new(route_params)
    @route.user = current_user
    if @route.save
      serialized_route = @route.to_global_id.to_s
      CreateRouteJob.perform_later(serialized_route)
      flash[:notice] = "Job enqueued"
      redirect_to bookmarks_path
      # case @route.destination.downcase
      # when "new zealand"
      #   # city_hash = [
      #   #   { 'city'=>'Auckland', 'country'=> 'New Zealand', 'days'=> 3 }
      #   # ]
      #   nz_hardcode_1(@route)
      #   nz_hardcode_2(@route)
      #   @route.destination = "New Zealand"
      #   @route.save
      #     # redirect_to route_path(@route)

      # else
      #   pick_cities(@route)
      # end
    end
  end

  private

  def route_params
    params.require(:route).permit(:budget, :start_date, :end_date, :destination, :no_of_people, :hotel_pref)
  end

  def pick_cities(route)
    destination = route.destination == "" ? Route.all.sample.days.sample.city : route.destination
    route.no_of_people = 2 if route.no_of_people == nil

    rooms = route.no_of_people.fdiv(2).ceil
    no_of_days = (route.end_date - route.start_date + 1).to_i
    no_of_cities = case no_of_days
                   when 1..4 then 1
                   when 5..7 then 2
                   when 8..10 then 3
                   else (no_of_days / 3).floor
                   end

    @cities = ChatgptService.call("
      I want to go on a vacation in #{destination}.
      Suggest #{no_of_cities} cities around to visit.
      Specify the country.
      Respond with just the entire response in JSON with a total of #{no_of_days} days.
      Example response for 3 cities with a total of 8 days:
      [
        { 'city'=>'Amsterdam', 'country'=> 'Netherlands', 'days'=> 3 },
        { 'city'=>'Rotterdam', 'country'=> 'Netherlands', 'days'=> 3 },
        { 'city'=>'Brussels', 'country'=> 'Belgium', 'days'=> 2 }
      ]
      Respond just with the JSON.")

      @cities = JSON.parse(@cities)
      # hotel_average_price = check_hotel_price(@cities.first["city"])
      hotel_average_price = 90

      generate_days(@cities, route, hotel_average_price, no_of_days)

  end

  def check_hotel_price(city)
    hotel_average_price = ChatgptService.call("
      Name any 3-star:hotelin #{city}.
      Convert price to Euro.
      Respond with just the entire response in JSON.
      Example response for Amsterdam:
      [{
        'name': 'Crowne Plaza Amsterdam Zuid',
        'price': 110,
        'coordinates': {
        'latitude': 56.358468,
        'longitude': 4.881119
        }
      }]
      Respond just with the JSON.
      ")

    hotel_average_price.include?("AI") ? 100 : JSON.parse(hotel_average_price).first["price"]
  end

  def generate_days(cities_hash, route, hotel_average_price, no_of_days)
    no_of_rooms = route.no_of_people.fdiv(2).ceil
    daily_hotel_budget = (route.budget - (25 * route.no_of_people * no_of_days)) / no_of_days / no_of_rooms

    hotel_description = case daily_hotel_budget / hotel_average_price * 100
                        when 0...50 then "Choose a hostel to stay."
                        when 50...100 then "Choose a 2-star hotel."
                        when 100...150 then "Choose a 3-star hotel."
                        when 150...300 then "Choose a 4-star hotel."
                        else "Choose a 5-star hotel."
                          # else "Choose a hotel with price from €#{hotel_price * 0.9} to €#{hotel_price}."
                        end

      country_array = []
      days = 1

      cities_hash.each do |hash|
        result = ChatgptService.call("
          Suggest #{hash["days"]} places to visit in #{hash["city"]}
          #{hotel_description}, convert all prices to euro.
          Include coordinates of the places recommended.
          Use only english language.
          Keep the description of the place within 250-300 characters.
          Be creative and inspire me.
          Respond with just the entire response in JSON.
          Example response:
          [{
            'city': '#{hash["city"]}',
            'country':'#{hash["country"]}',
            'hotel': {
              'name': 'Crowne Plaza Amsterdam Zuid',
              'room_type': 'Twin Room',
              'no_of_people_per_room': 2,
              'price': 110,
              'description': '5 star hotel located in the east of Amsterdam, it has a lively bar, a private garden, a restaurant and a terrace. It is within walking distance of many restaurants, bars and clubs.',
              'coordinates': {
                'latitude': 56.358468,
                'longitude': 4.881119
              }
            },
            'activity1': {
              'name': 'Grand Place',
              'price': 0,
              'description': 'Much of the square's elegant character is due to the unique architecture of its elegant Gildehuizen (guild houses) with their magnificent gables, pilasters, and balustrades, ornately carved stonework, and rich gold decoration.',
              'coordinates': {
                'latitude': 52.358468,
                'longitude': 4.881119
              }
            },
            ...,
            'activity#{hash["days"]}': {
              'name': 'Grand Place',
              'price': 0,
              'description': 'Much of the square's elegant character is due to the unique architecture of its elegant Gildehuizen (guild houses) with their magnificent gables, pilasters, and balustrades, ornately carved stonework, and rich gold decoration.',
              'coordinates': {
                'latitude': 52.358468,
                'longitude': 4.881119
              }
            }
          }]
          Respond just with the JSON.")

        result = JSON.parse(result).first

        hash["days"].times do |i|
          day = Day.new(route: route, city: hash["city"])
          day.nation = result["country"]
          day.name_hotel = result["hotel"]["name"]
          day.description_hotel = result["hotel"]["description"]
          day.price_hotel = result["hotel"]["price"]
          day.room_type = result["hotel"]["room_type"]
          day.no_of_rooms = route.no_of_people.fdiv(result["hotel"]["no_of_people_per_room"]).ceil
          day.latitude_hotel = result["hotel"]["coordinates"]["latitude"]
          day.longitude_hotel = result["hotel"]["coordinates"]["longitude"]

          day.name = result["activity#{i + 1}"]["name"]
          day.description = result["activity#{i + 1}"]["description"]
          day.price = result["activity#{i + 1}"]["price"]
          day.latitude = result["activity#{i + 1}"]["coordinates"]["latitude"]
          day.longitude = result["activity#{i + 1}"]["coordinates"]["longitude"]
          day.sequence = days
          days += 1

          day.save

          country_array << day.nation unless country_array.include?(day.nation)
          route.total_price += ( day.price * route.no_of_people + day.price_hotel * day.no_of_rooms)
        end
      end
    assign_destination_to_route(route, country_array)
  end

  def nz_hardcode_1(route)
    result = {
      'city': 'Auckland',
      'country': 'New Zealand',
      'hotel': {
        'name': 'The Grand by SkyCity',
        'room_type': 'Deluxe Queen Room',
        'no_of_people_per_room': 2,
        'price': 195.42,
        'description': 'Located in the heart of Auckland, The Grand by SkyCity offers impeccable service and luxurious amenities such as a 25-metre heated lap pool, fitness centre and sauna. This 5-star hotel is within walking distance of the city\'s top attractions.',
        'coordinates': {
          'latitude': -36.8485,
          'longitude': 174.7708
        }
      },
      'activity1': {
        'name': 'Auckland Domain',
        'price': 0,
        'description': 'One of Auckland\'s oldest and largest parks, the Auckland Domain features beautiful gardens, walking trails, historic monuments and the Auckland War Memorial Museum. It\'s the perfect place to relax and take in the natural beauty of the city.',
        'coordinates': {
          'latitude': -36.8642,
          'longitude': 174.7708
        }
      },
      'activity2': {
        'name': 'Auckland Harbour Bridge',
        'price': 141.65,
        'description': 'Climb to the top of Auckland Harbour Bridge, 67 metres above the sparkling Waitemata Harbour. This unforgettable experience also includes a commentary on the bridge\'s history and engineering, as well as stunning panoramic views.',
        'coordinates': {
          'latitude': -36.8203,
          'longitude': 174.7617
        }
      },
      'activity3': {
        'name': 'Sky Tower',
        'price': 32.25,

app/views/routes/_day_info.html.erb
<div  class="flex justify-between">
                <h4 class="text-lg font-medium mb-2"><%= day.name %></h4>
                <% if (current_user == @route.user) && @route.booking.nil? %>
                  <%= simple_form_for day, :url => day_change_activity_path(day) do |f| %>
                    <%= f.submit "Change activity", class: "text-xs cursor-pointer transition duration-500 mx-2 px-3 py-2 text-mainYellow font-medium rounded-lg hover:bg-darkerYellow hover:text-white focus:outline-none" %>
                  <% end %>
                <% end %>
              </div>

app/views/routes/_first_marker.html.erb
<div class="rounded-full bg-darkerYellow">
  <h2><%= day.name %></h2>
  <p><%= day.description %></p>
</div>

app/views/routes/_hotel_info.html.erb
<div  class="flex justify-between bg-darYellow">
  <h4 class="text-lg font-medium mb-2">Accommodation: <br><%= day.name_hotel %> <br>(<%= day.no_of_rooms %> x <%= day.room_type %>)</h4>
  <div class="pt-2" >
    <p class="text-gray-600 font-medium text-end px-3">Price: €<%= day.price_hotel %></p>
  </div>
</div>
<p class="text-gray-600 mb-2"><i><%= day.description_hotel %></i></p>

app/views/routes/_info_window.html.erb
<h2><%= day.name %></h2>
<p><%= day.description %></p>

app/views/routes/_logo_marker.html.erb
<img src="https://source.unsplash.com/random/1200x800/?<%= day.city %>" alt="Image of city" width="30" height="30">

app/views/routes/_summary_route.html.erb
<div class="sticky top-0 bg-white border-b-2 z-10">

  <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <a href="#">
        <img class="rounded-t-lg" src="/docs/images/blog/image-1.jpg" alt="" />
    </a>
    <div class="p-5">
        <a href="#">
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
        </a>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
        <a href="#" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            Read more
            <svg aria-hidden="true" class="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </a>
    </div>
</div>


  <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8 flex justify-between items-center">
    <div class="w-1/2">
      <h1 class="text-3xl font-bold mb-2">Your Route</h1>
      <h4 class="text-gray-600 mb-2">Your Budget: €<%= @route.budget %></h4>
      <h4 class="text-gray-600 mb-2">Total Price: €<%= @route.total_price.round(2) %></h4>
      <h4 class="text-gray-600 mb-2"><%= @route.no_of_people %> People</h4>
      <h4 class="text-gray-600 mb-2"><%= @route.hotel_pref %></h4>
    </div>
    <%= simple_form_for [@route, @bookmark] do |f| %>
      <div class="flex items-center">
        <%= f.submit "Bookmark", class: "px-4 py-2 bg-mainYellow text-white rounded-lg hover:bg-darkerYellow focus:bg-darkerYellow focus:outline-none" %>
      </div>
    <% end %>
  </div>

  <div class="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between items-center">
      <div class="w-1/2 h-0.5 bg-gray-300"></div>
      <% @days.each do |day| %>
        <div class="flex items-center ml-4">
          <div class="w-2 h-2 rounded-full bg-mainYellow"></div>
          <h4 class="text-gray-600 font-medium text-sm ml-2"><%= day.city %></h4>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/routes/index.html.erb
<h1> Routes </h1>
<ul>
  <% @routes.each do |route| %>
    <li><%= link_to route.destination, route_path(route) %></li>
  <% end %>
</ul>

app/views/routes/new.html.erb
<h1>New Routes nice</h1>

<%=  %>

app/views/routes/show.html.erb
<%= render "shared/navbar" %>

<%# <div data-controller="gpt-response"> %>
  <section id="main-banner" class="h-screen w-full items-center bg-black">
      <%= video_tag "airport.mp4", autoplay: :autoplay, loop: :loop, muted: :muted, class: "w-full h-full object-cover absolute z-0 opacity-40" %>

    <div class="container mx-auto p-8 pt-16 px-40 relative z-10" style="cursor: auto;">
      <div class="flex flex-wrap items-center">
        <div class="w-full pt-4 flex flex-col justify-between">

          <div class="flex flex-inline justify-between pb-10">
            <% if current_user == @route.user %>
              <div class="">
                <div class="mb-5">
                  <% if @route.booking != nil %>
                    <h6 class="text-sm font-semibold text-darkerYellow bg-white px-3 py-2 rounded-lg inline"><i class="fa-check fa-solid mr-2 text-darkerYellow"></i>Booked!</h6>
                  <% elsif @route.bookmark != nil %>
                    <h6 class="text-sm font-semibold text-darkerYellow bg-white px-3 py-2 rounded-lg inline"><i class="fa-bookmark fa-solid mr-2 text-darkerYellow"></i>Bookmarked</h6>
                  <% end %>
                </div>
                <h4 class="text-2xl font-normal mb-2 text-white">Your trip:</h4>

                <div class="flex justify-between">
                  <div>
                    <h4 class="text-4xl font-semibold mb-2 text-white"><%= @route.start_date.strftime("%-d %b") %> - <%= @route.end_date.strftime("%d %b %Y") %></h4>
                  </div>
                  <div class="flex items-center">
                    <h5 class="inline-block px-2 py-1 mr-2 mb-2 px-3 py-1 leading-none bg-gray-300 text-gray-600 rounded-full font-semibold tracking-wide text-s"><i class="far fa-user fa-fw"></i>x<%= @route.no_of_people %></h5>
                  </div>
                </div>
                <div class="flex">
                    <h5 class="text-xl font-semibold mb-2 mr-2 text-white">Price: €<%= @route.total_price.round() %></h5>
                    <br>
                    <h5 class="text-xl font-normal mb-2 text-white"><small>(Your budget: €<%= @route.budget.round() %>)</small></h5>
                </div>
                <ul class="day-order fa-ul text-xs mt-4 list-disc list-inside text-gray-50 leading-relaxed" data-controller="sortable change-list-color">
                  <% @days.each_with_index do |day, i| %>
                    <li data-id="<%= day.id %>" class="text-lg font-semibold cursor-move"><span class="fa-li"><i class="fa-solid fa-arrows-up-down-left-right"></i></span>Day <%= i + 1 %> - <%= day.name %><small>, <%= day.city %>, <%= day.nation %></small></li>
                  <% end %>
                </ul>
                  <% if @route.booking.nil? %>
                    <%= form_with url: "/update_sequence", method: :patch do |form| %>
                      <%= form.hidden_field :days_order, id: "day-order" %>
                      <%= form.submit "Update route", class: "cursor-pointer transition duration-500 mt-4 px-3 py-2 text-darkerYellow font-medium rounded-lg hover:bg-darkerYellow hover:text-white hover:border-darkerYellow focus:outline-none" %>
                    <% end %>
                  <% end %>
              </div>
            <% else %>
              <div>
                <h4 class="text-4xl font-semibold mb-2 text-white">Itinerary</h4>
                <h5 class="text-xl font-semibold mb-2 text-white"><i class="far fa-user fa-fw"></i> <%= @route.no_of_people %></h5>
                <h5 class="text-xl font-semibold mb-2 text-white">Total Price: €<%= @route.total_price.round() %></h5>
                <div class="flex flex-wra p text-center pt-4 mb-2">
                  <% @countries.each do |country| %>
                      <div class="inline-block px-2 py-1 mr-2 mb-2 px-3 py-1 leading-none bg-orange-200 text-orange-800 rounded-full font-semibold uppercase tracking-wide text-xs">
                        <%= country %>
                      </div>
                  <% end %>
                </div>
                <ul class="day-order text-xs mt-4 list-disc list-inside text-gray-50 leading-relaxed">
                  <% @days.each_with_index do |day, i| %>
                    <li data-id="<%= day.id %>" class="text-lg font-semibold">Day <%= i + 1 %> - <%= day.name %><small>, <%= day.city %>, <%= day.nation %></small></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

              <div class="w-6/12 h-96">
                <%= render "shared/map" %>
                <div class="flex flex-wrap text-center py-2">
                  <% @countries.each do |country| %>
                      <div class="inline-block px-2 py-1 mr-2 mb-2 px-3 py-1 leading-none bg-gray-300 text-gray-600 rounded-full font-semibold uppercase tracking-wide text-xs">
                        <%= country %>
                      </div>
                  <% end %>
                </div>
              </div>

          </div>

            <div class="w-full pt-4">
              <% if current_user == @route.user %>
                <% if @route.bookmark.nil? %>
                  <%= simple_form_for [@route, @bookmark], class: "sticky top-10" do |f| %>
                    <%= f.button :submit, "Bookmark", class: "cursor-pointer w-full block text-center relative text-white font-bold bg-mainYellow px-4 py-3 rounded-lg shadow-lg hover:shadow-none hover:opacity-100 opacity-75 transition duration-500 "%>
                  <% end %>
                <% elsif @route.booking.nil? %>
                  <%= simple_form_for [@route.bookmark, @booking], class: "sticky top-10" do |f| %>
                    <%= f.button :submit, "Book!", class: "cursor-pointer w-full block text-center relative text-white font-bold bg-mainYellow px-4 py-3 rounded-lg shadow-lg hover:shadow-none hover:opacity-100 opacity-75 transition duration-500 " %>
                  <% end %>
                <% else %>
                  <%= link_to "View Booking Confirmation", booking_path(@route.booking), class: "cursor-pointer w-full block text-center relative text-white font-bold bg-mainYellow px-4 py-3 rounded-lg shadow-lg hover:shadow-none hover:opacity-100 opacity-75 transition duration-500 " %>
                  <%# <h3 class="sticky top-10 w-full block text-center relative text-white font-bold bg-mainYellow px-4 py-3 rounded-lg shadow-lg">You have booked this trip!</h3> %>
                <% end %>
              <% else %>
                <%= simple_form_for [@route, @bookmark] do |f| %>
                  <%= f.button :submit, "Bookmark to customize the trip!", class: "cursor-pointer w-full block text-center relative text-white font-bold bg-mainYellow px-4 py-3 rounded-lg shadow-lg hover:shadow-none hover:opacity-100 opacity-75 transition duration-500 "%>
                <% end %>
              <% end %>
            </div>



        </div>
      </div>
    </div>
  </section>

        <% @days.each_with_index do |day, i| %>
  <div class="container mx-auto p-8 px-40" >
          <div class=" border-b-2 rounded-lg mb-10 flex p-8 hover:shadow-2xl hover:bg-veryLightGray hover:scale-110 transition duration-1000 ease-in-out">
            <div class="w-1/2">
              <h4 class="text-2xl font-semibold mb-2">Day <%= i + 1 %> - <%= day.city %>, <%= day.nation %></h4>
              <%= render "shared/display_weather", day: day %>
              <%# <div  class="flex justify-between"> %>
              <div  class="flex justify-between bg-darYellow">
                  <h4 class="text-lg font-medium mb-2"><%= day.name %></h4>
                    <div class="" >
                      <p class="inline-block px-2 py-1 mr-2 mb-2 px-3 py-1 leading-none bg-gray-300 text-gray-600 rounded-full font-semibold uppercase tracking-wide text-xs"><%= day.price == 0 ? "No entrance fee" : "Entrance fee per person: €#{day.price.round()}" %></p>
                    </div>
                  </div>
              <%# </div> %>
              <p class="text-gray-600 mb-2"><i><%= day.description %></i></p>
              <div  class="flex justify-end">
                <% if (current_user == @route.user) && @route.booking.nil? %>
                  <%= simple_form_for day, :url => day_change_activity_path(day) do |f| %> <%#, html: { data: { action: "submit->change-hotel#change" } }%>
                      <%# <%= f.hidden_field :authenticity_token, value: form_authenticity_token %>
                    <%= f.submit "Change activity", class: "text-xs cursor-pointer transition duration-500 mx-2 px-3 py-2 text-mainYellow font-medium rounded-lg hover:bg-darkerYellow hover:text-white focus:outline-none" %>
                  <% end %>
                <% end %>
              </div>
              <%# <p class="text-gray-600 mb-2"><i><%= day.description %>
              <%# <p class="text-gray-600 font-medium"><%= day.price == 0 ? "No entrance fee" : "Entrance fee per person: €#{day.price.round(2)}" %>
              <hr class="mt-2 mb-4">
              <div data-controller="change-hotel">
                <div id="hotel-info" data-change-hotel-target="display" class="hotel_info">
                  <div  class="flex justify-between">
                    <h4 class="text-lg font-medium mb-2">Accommodation: <br><%= day.name_hotel %> <br>(<%= day.no_of_rooms %> x <%= day.room_type %>)</h4>
                    <div class="" >
                      <p class="inline-block px-2 py-1 mr-2 mb-2 px-3 py-1 leading-none bg-gray-300 text-gray-600 rounded-full font-semibold uppercase tracking-wide text-xs">Price: €<%= day.price_hotel.round() %></p>
                    </div>
                  </div>
                  <p class="text-gray-600 mb-2"><i><%= day.description_hotel %></i></p>
                </div>

                <% if (current_user == @route.user) && @route.booking.nil? %>
                  <div class="grid justify-items-end">
                    <div class="inline-flex">
                      <%= simple_form_for day, :url => day_upgrade_hotel_path(day), html: { data: { action: "submit->change-hotel#update" } } do |f| %>
                        <%= f.submit "Upgrade accommodation", class: "text-xs cursor-pointer transition duration-500 mx-2 px-3 py-2 text-mainYellow font-medium rounded-lg hover:bg-darkerYellow hover:text-white focus:outline-none" %>
                      <% end %>
                      <%= simple_form_for day, :url => day_downgrade_hotel_path(day), html: { data: { action: "submit->change-hotel#update" } } do |f| %>
                        <%= f.submit "Find a cheaper option", class: "text-xs cursor-pointer transition duration-500 mx-2 px-3 py-2 text-mainYellow font-medium rounded-lg hover:bg-darkerYellow hover:text-white focus:outline-none" %>
                      <% end %>
                    </div>
                  </div>
                <% end %>

              </div>
            </div>
            <div class="w-1/2 flex justify-end">
              <div class="rounded-lg shadow-lg p-6 h-3/4 bg-white hover:shadow-2xl hover:scale-125 hover:-translate-x-32 hover:translate-y-8	transition duration-1000 ease-in-out">
                <img src="https://source.unsplash.com/random/90<%= rand(0..9) %>x60<%= rand(0..9) %>/?<%= day.city %>" alt="Image of city" width="300" height="300" class="">
                <%# <p class="text-sm text-center pt-8"><i>Pic of <%= day.city %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>

<%# Button For Strip payment %>